### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/shifthelper#58]
- [ ] Implement tests, see #26 
- [ ] setup CI
- [ ] cloud detection, see #46 and #51 
- [ ] trigger rates, see #22 
- [ ] check ratescans, see #9 
- [ ] Timestamps, see #7 
- [ ] Retry connections before calling the shifter, see #56 
- [ ] Remove Current limits from config file, see #65
- [ ] Redundancy, c.f #53 #54 #55 

please add stuff that should be done or talked about and discuss about priorities.

**Comment by dneise** [comment]
Max N: when sleep AND good weather, then call shifter --> Take data you lazy fool

**Comment by MaxNoe** [comment]
This issue is stupid. This is what milestones are for.
